version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db_stocksage
    restart: always
    environment:
      POSTGRES_DB: stock_tracker_db
      POSTGRES_USER: stockuser
      POSTGRES_PASSWORD: stockpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache_stocksage
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_stock_sage
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # Change to your email
      PGADMIN_DEFAULT_PASSWORD: admin123  # Change to a strong password
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:
